//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorPOC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorPOC.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Language.
        /// </summary>
        internal static string ChangeLanguageNav {
            get {
                return ResourceManager.GetString("ChangeLanguageNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter.
        /// </summary>
        internal static string Counter {
            get {
                return ResourceManager.GetString("Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter.
        /// </summary>
        internal static string CounterNav {
            get {
                return ResourceManager.GetString("CounterNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Feedback.
        /// </summary>
        internal static string FeedbackNav {
            get {
                return ResourceManager.GetString("FeedbackNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch Data.
        /// </summary>
        internal static string FetchDataNav {
            get {
                return ResourceManager.GetString("FetchDataNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello World.
        /// </summary>
        internal static string HelloWorld {
            get {
                return ResourceManager.GetString("HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to your new app..
        /// </summary>
        internal static string HelloWorldText {
            get {
                return ResourceManager.GetString("HelloWorldText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en.
        /// </summary>
        internal static string HomeHref {
            get {
                return ResourceManager.GetString("HomeHref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomeNav {
            get {
                return ResourceManager.GetString("HomeNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required..
        /// </summary>
        internal static string requiredField {
            get {
                return ResourceManager.GetString("requiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breadth must be between 0 and 100.
        /// </summary>
        internal static string VesselBreadthError {
            get {
                return ResourceManager.GetString("VesselBreadthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The breadth should be numeric..
        /// </summary>
        internal static string VesselBreadthNumeric {
            get {
                return ResourceManager.GetString("VesselBreadthNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vessel Dimension.
        /// </summary>
        internal static string VesselDimensionNav {
            get {
                return ResourceManager.GetString("VesselDimensionNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vessel Dimensions.
        /// </summary>
        internal static string VesselDimensions {
            get {
                return ResourceManager.GetString("VesselDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length must be between 0 and 100.
        /// </summary>
        internal static string VesselLengthError {
            get {
                return ResourceManager.GetString("VesselLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather forecast.
        /// </summary>
        internal static string Weatherforecast {
            get {
                return ResourceManager.GetString("Weatherforecast", resourceCulture);
            }
        }
    }
}
